Using  cuda
torch.Size([4, 508, 7, 7])
24892
torch.Size([4, 24892])
Traceback (most recent call last):
  File "src/sweep_test.py", line 138, in <module>
    main()
  File "src/sweep_test.py", line 103, in main
    outputs = model(inputs)
  File "/usr/common/software/pytorch/v1.2.0-gpu/lib/python3.6/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/global/u2/d/danieltm/Pipeline_Toy/src/models/convNet.py", line 26, in forward
    x = F.relu(self.fc1(x))
  File "/usr/common/software/pytorch/v1.2.0-gpu/lib/python3.6/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/common/software/pytorch/v1.2.0-gpu/lib/python3.6/site-packages/torch/nn/modules/linear.py", line 87, in forward
    return F.linear(input, self.weight, self.bias)
  File "/usr/common/software/pytorch/v1.2.0-gpu/lib/python3.6/site-packages/torch/nn/functional.py", line 1369, in linear
    ret = torch.addmm(bias, input, weight.t())
RuntimeError: size mismatch, m1: [4 x 24892], m2: [7 x 2570] at /global/cscratch1/sd/swowner/pytorch-build/pytorch/v1.2.0-gpu/pytorch/aten/src/THC/generic/THCTensorMathBlas.cu:273
